# 全局配置
jwt.secret: "Ziyouyanfa!@#"
mq.host: 127.0.0.1       
api.host: 127.0.0.1
  
---
spring:
  profiles: local
      
mq.host: 192.168.1.170
logging.level.naf.cloud.gateway.*: DEBUG

---
spring:
  profiles: dev
      
mq.host: 127.0.0.1
logging.level.naf.cloud.gateway.*: DEBUG

---
spring:
  profiles: prod
      
mq.host: 192.168.1.190
        
---
spring:
  profiles: weixin-local
  profiles.include: weixin, local

---
spring:
  profiles: weixin-dev
  profiles.include: weixin, dev

---
spring:
  profiles: weixin-prod
  profiles.include: weixin, prod        
  
---
spring:
  profiles: platform-local
  profiles.include: platform, local
  
---
spring:
  profiles: platform-dev
  profiles.include: platform, dev
  
---
spring:
  profiles: platform-prod
  profiles.include: platform, prod
  
---
spring:
  profiles: www-local
  profiles.include: www, local
  
---
spring:
  profiles: www-dev
  profiles.include: www, dev
  
---
spring:
  profiles: www-prod
  profiles.include: www, prod
    