
---
server.port: 8000

spring:
  profiles: platform
  cloud:
    gateway:
      default-filters:
      #- PrefixPath=/httpbin
      #- JwtParser=.*/login
      - AddResponseHeader=Cache-Control, no-cache
      - AddResponseHeader=Pragma, no-cache
      - AddResponseHeader=Expires, -1
      - HostToTenant=^([0-9]{5}).smart.*

      routes:
      # RabbitMQ Websocket route
      - id: websocket_route
        #uri: ws://192.168.1.190:15674
        uri: ws://${mq.host}:15674
        predicates:
        - Path=/ws/**      
      ##############################################
      #             业务管理平台管理                            #
      ##############################################        
      # == 管理接口-字典管理接口服务 ==
      - id: system_dict
        uri: http://${api.host}:8002
        order: 9000
        predicates:
        - Path=/platform/api/system/dict/**
        filters:
        - RewritePath=/.*/api/system/dict/(?<segment>.*), /$\{segment}
        - JwtParser
      # == 管理接口-系统管理默认接口服务（naf_user）==
      - id: system_default
        uri: http://${api.host}:8001
        order: 9100
        predicates:
        - Path=/platform/api/system/**
        filters:
        - RewritePath=/.*/api/system/(?<segment>.*), /$\{segment}
        - name: JwtParser
          args:
              ignore: .*/login
              order: -1
      # == 内部接口-微信扫码登录（naf_weixin）==
      - id: internal_weixin
        uri: http://${api.host}:8001
        order: 9100
        predicates:
        - RemoteAddr=192.168.1.1/16, 127.0.0.1/32
        - Path=/platform/api/weixin/**
        filters:
        - RewritePath=/.*/weixin/(?<segment>.*), /weixin/$\{segment}
      # == 公共接口-NAF字典接口服务 ==
      - id: api_naf_dict
        uri: http://${api.host}:8002
        order: 9000
        predicates:
        - Path=/platform/api/naf/dict/**
        filters:
        - RewritePath=/.*/api/naf/dict/(?<segment>.*), /api/$\{segment}
      # == 公共接口-NAF用户相关接口服务（naf_user）==
      - id: api_naf_default
        uri: http://${api.host}:8001
        order: 9200
        predicates:
        - Path=/platform/api/naf/**
        filters:
        - RewritePath=/.*/api/naf/(?<segment>.*), /api/$\{segment}
      # == 管理接口-学生库服务（platform-user）==
      - id: admin_api_user
        uri: http://${api.host}:8101
        order: 9000
        predicates:
        - Path=/platform/api/jobs/user/**
        filters:
        - RewritePath=/.*/api/jobs/user/(?<segment>.*), /admin/$\{segment}
      # == 管理接口-企业库服务（platform-corp）==
      - id: admin_api_corp
        uri: http://${api.host}:8102
        order: 9000
        predicates:
        - Path=/platform/api/jobs/corp/**
        filters:
        - RewritePath=/.*/api/jobs/corp/(?<segment>.*), /admin/$\{segment}
      # == 管理接口-招聘相关接口服务（jobs-service）==
      - id: admin_api_jobs
        uri: http://${api.host}:8201
        order: 9100
        predicates:
        - Path=/platform/api/jobs/**
        filters:
        - RewritePath=/.*/api/jobs/(?<segment>.*), /admin/$\{segment}
      # == 管理接口-公文系统相关接口服务（docflow-srv）==
      - id: admin_api_docflow
        uri: http://${api.host}:8301
        order: 9000
        predicates:
        - Path=/platform/api/docflow/**
        filters:
        - RewritePath=/.*/api/docflow/(?<segment>.*), /$\{segment}
        - JwtParser
        
      # == 管理平台微信扫码登录 ==
      - id: platform_weixin
        uri: http://localhost:3300
        order: 9900
        predicates:
        - Path=/platform/weixin/**
#      # == 省级平台管理前端 ==
#      - id: master_platform_admin
#        uri: http://localhost:3100
#        order: 10000
#        predicates:
#        - Path=/platform/**
#        - Host=smart.**
#        filters:
#        - AddRequestHeader=X-Tenant, master
#      # == 二级多租户平台管理前端 ==
#      - id: master_platform_admin
#        uri: http://localhost:3200
#        order: 10000
#        predicates:
#        - Host=*.smart.**
#        - Path=/platform/**
        
        
      ##############################################
      #                  前端接口                                 #
      ##############################################        
      # == 框架接口-NAF字典接口服务 ==
      - id: naf_code
        uri: http://${api.host}:8002
        order: 9000
        predicates:
        - Path=/www/api/naf/code/**
        filters:
        - RewritePath=/www/api/naf/code/(?<segment>.*), /api/$\{segment}
      # == 框架接口-NAF分站接口服务 ==
      - id: naf_unit
        uri: http://${api.host}:8001
        order: 9000
        predicates:
        - Path=/www/api/naf/unit/**
        filters:
        - RewritePath=/www/api/naf/unit/(?<segment>.*), /api/unit/$\{segment}
